[package]
name = "sealantern"
version = "1.2.0"
description = "Minecraft Server Manager"
authors = ["FPS_Z"]
edition = "2021"
default-run = "sealantern"

[lib]
name = "sealantern_lib"
crate-type = ["lib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.9", features = ["macos-private-api", "protocol-asset"] }
tauri-plugin-dialog = "2.6"
tauri-plugin-fs = "2.4"
tauri-plugin-http = "2.5"
tauri-plugin-opener = "2.5"
tauri-plugin-process = "2.3"
tauri-plugin-window-state = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
uuid = "1"
tokio = { version = "1", features = ["time"] }
sealantern-extra = { path = "../crates/extra" }
sealantern-core = { path = "../crates/core" }
sealantern-infra = { path = "../crates/infra" }

[features]
docker = []
