use sea_lantern_server_config_core::properties::write_properties;
use sea_lantern_server_config_core::startup::{read_server_port, update_pumpkin_config_if_present};
use std::collections::HashMap;
use std::path::Path;

use crate::services::server::manager::provisioning::i18n::provisioning_t1;

pub(super) fn ensure_server_properties_for_import(
    run_dir: &Path,
    requested_port: u16,
    online_mode: bool,
) -> Result<u16, String> {
    if update_pumpkin_config_if_present(run_dir, requested_port, online_mode)
        .map_err(|e| provisioning_t1("server.provisioning.update_server_properties_failed", e))?
    {
        return Ok(read_server_port(run_dir, requested_port));
    }

    let server_properties_path = run_dir.join("server.properties");
    if server_properties_path.exists() {
        let port = read_server_port(run_dir, requested_port);
        let mut updates = HashMap::new();
        updates.insert("online-mode".to_string(), online_mode.to_string());
        write_properties(server_properties_path.to_str().unwrap_or_default(), &updates).map_err(
            |e| {
                provisioning_t1(
                    "server.provisioning.update_server_properties_failed",
                    e.to_string(),
                )
            },
        )?;
        return Ok(port);
    }

    let content = format!(
        "# Minecraft server properties\n# Generated by SeaLantern\nserver-port={}\nonline-mode={}\n",
        requested_port, online_mode
    );
    std::fs::write(&server_properties_path, content).map_err(|e| {
        provisioning_t1("server.provisioning.create_server_properties_failed", e.to_string())
    })?;

    Ok(requested_port)
}
