#[cfg(test)]
pub(crate) fn example_local_plugin_info(
    plugin_root: &std::path::Path,
    state: crate::plugins::manager::PluginState,
) -> crate::models::plugin::PluginInfo {
    crate::models::plugin::PluginInfo {
        manifest: crate::models::plugin::PluginManifest {
            id: "example-plugin".to_string(),
            name: "Example Plugin".to_string(),
            version: "1.0.0".to_string(),
            description: "test plugin".to_string(),
            author: crate::models::plugin::PluginAuthor {
                name: "tester".to_string(),
                email: None,
                url: None,
            },
            main: "main.lua".to_string(),
            license: None,
            homepage: None,
            repository: None,
            engines: None,
            permissions: Vec::new(),
            ui: None,
            events: Vec::new(),
            commands: Vec::new(),
            programs: Vec::new(),
            dependencies: Vec::new(),
            optional_dependencies: Vec::new(),
            icon: None,
            settings: None,
            sidebar: None,
            locales: None,
            include: Vec::new(),
            capabilities: Vec::new(),
            theme_var_map: std::collections::HashMap::new(),
            presets: std::collections::HashMap::new(),
            server_events: std::collections::HashMap::new(),
        },
        state,
        path: plugin_root.to_string_lossy().to_string(),
        source: crate::models::plugin::PluginSource::Local,
        runtime: crate::models::plugin::PluginRuntimeKind::Lua,
        actions: crate::models::plugin::PluginActions {
            can_toggle: true,
            can_delete: true,
            can_check_update: true,
        },
        missing_dependencies: Vec::new(),
        trust_level_display: crate::models::plugin::PluginTrustLevelDisplay::StandardSandbox,
        execution_class: crate::models::plugin::PluginExecutionClass::Sandboxed,
        review_status: crate::models::plugin::PluginReviewStatus::Unreviewed,
        integrity_status: crate::models::plugin::PluginIntegrityStatus::Unknown,
        trusted_policy_source: crate::models::plugin::PluginTrustedPolicySource::None,
        permission_profile: crate::models::plugin::PluginPermissionProfile::SandboxedNormal,
        publisher_id: None,
        distribution_class: crate::models::plugin::PluginDistributionClass::LocalDirectory,
        trusted_catalog_matched: false,
        hash_matched: false,
        verified_hash: None,
        verified_signature: false,
        reviewed_at: None,
        revoked: false,
        exceeds_standard_sandbox: false,
        requires_explicit_consent: false,
    }
}
