use crate::commands;

/// Debug-only command module excluded from release builds.
#[cfg(debug_assertions)]
use commands::app::debug as debug_commands;

use commands::app::host as system_commands;
use commands::app::i18n as i18n_commands;
use commands::app::logging as logging_commands;
use commands::app::settings as settings_commands;
use commands::downloads::java as java_commands;
use commands::downloads::mods as mod_download_commands;
use commands::downloads::transfers as download_commands;
use commands::online::join as join_commands;
use commands::online::server_ids as server_id_commands;
use commands::online::tunnel as tunnel_commands;
use commands::plugins::manage as plugin_commands;
use commands::server::config as config_commands;
use commands::server::extensions as extensions_commands;
use commands::server::manage as server_commands;
use commands::server::players as player_commands;
use commands::server::plugins as server_plugin_commands;
use commands::update as update_commands;

/// Registers the Tauri desktop command table.
///
/// The returned handler is the authoritative desktop IPC surface and should stay
/// aligned with the frontend command wrappers and runtime command catalog.
pub(crate) fn desktop_handler(
) -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        server_commands::create_server,
        server_commands::import_server,
        server_commands::add_existing_server,
        server_commands::import_modpack,
        server_commands::parse_server_core_key,
        server_commands::parse_server_core_type,
        server_commands::scan_startup_candidates,
        server_commands::collect_copy_conflicts,
        server_commands::copy_directory_contents,
        server_commands::start_server,
        server_commands::stop_server,
        server_commands::restart_server,
        server_commands::prepare_force_stop_server,
        server_commands::force_stop_server,
        server_commands::send_command,
        server_commands::get_server_list,
        server_commands::get_server_status,
        server_commands::delete_server,
        server_commands::delete_server_record_only,
        server_commands::delete_server_with_files,
        server_commands::get_server_logs,
        server_commands::get_local_launch_detail,
        server_commands::get_docker_launch_detail,
        server_commands::update_server_name,
        server_commands::update_server_java_path,
        server_commands::validate_server_path,
        server_commands::update_server_path,
        java_commands::detect_java,
        java_commands::validate_java_path,
        java_commands::install_java,
        java_commands::cancel_java_install,
        mod_download_commands::search_mods,
        mod_download_commands::install_mod,
        config_commands::read_config,
        config_commands::list_server_config_files,
        config_commands::search_server_config_files,
        config_commands::read_server_config_source,
        config_commands::write_server_config_source,
        config_commands::read_server_config_document,
        config_commands::write_server_config_document,
        config_commands::write_config,
        config_commands::read_server_properties,
        config_commands::write_server_properties,
        config_commands::read_server_properties_source,
        config_commands::write_server_properties_source,
        config_commands::parse_server_properties_source,
        config_commands::preview_server_properties_write,
        config_commands::preview_server_properties_write_from_source,
        config_commands::read_sl_config,
        config_commands::write_sl_config,
        extensions_commands::get_server_extensions_summary,
        system_commands::get_system_info,
        system_commands::get_host_capabilities,
        system_commands::get_desktop_web_status,
        system_commands::get_server_resource_usage,
        system_commands::list_event_consumers,
        system_commands::get_event_consumer,
        system_commands::get_recent_app_operation_events,
        system_commands::set_event_consumer_enabled,
        system_commands::update_event_consumer_filters,
        system_commands::update_event_consumer_metadata,
        system_commands::pick_jar_file,
        system_commands::pick_archive_file,
        system_commands::pick_startup_file,
        system_commands::pick_server_executable,
        system_commands::pick_java_file,
        system_commands::pick_save_file,
        system_commands::pick_personalization_export_file,
        system_commands::pick_personalization_import_file,
        system_commands::pick_folder,
        system_commands::pick_file,
        system_commands::pick_image_file,
        system_commands::open_file,
        system_commands::open_folder,
        system_commands::get_default_run_path,
        system_commands::get_app_version,
        system_commands::get_create_server_defaults,
        system_commands::get_safe_mode_status,
        system_commands::frontend_heartbeat,
        system_commands::test_ipv6_connectivity,
        i18n_commands::get_locale_bundle,
        player_commands::get_whitelist,
        player_commands::get_banned_players,
        player_commands::get_banned_ips,
        player_commands::get_ops,
        player_commands::get_server_player_summary,
        player_commands::parse_player_log_events,
        player_commands::add_to_whitelist,
        player_commands::remove_from_whitelist,
        player_commands::ban_player,
        player_commands::unban_player,
        player_commands::add_op,
        player_commands::remove_op,
        player_commands::kick_player,
        player_commands::export_logs,
        settings_commands::get_settings,
        settings_commands::get_data_dir_status,
        settings_commands::initialize_data_dir,
        settings_commands::change_data_dir,
        settings_commands::get_plugin_dir_status,
        settings_commands::change_plugin_dir,
        settings_commands::save_settings,
        settings_commands::save_settings_with_diff,
        settings_commands::update_settings_partial,
        settings_commands::reset_settings,
        settings_commands::export_settings,
        settings_commands::import_settings,
        settings_commands::export_personalization_package,
        settings_commands::import_personalization_package,
        settings_commands::get_personalization_package_suggested_name,
        settings_commands::get_system_fonts,
        settings_commands::get_plugin_console_commands,
        settings_commands::update_plugin_console_commands,
        settings_commands::get_plugin_commands,
        settings_commands::update_plugin_commands,
        settings_commands::apply_acrylic,
        settings_commands::apply_window_effect,
        tunnel_commands::tunnel_host,
        tunnel_commands::tunnel_join,
        tunnel_commands::tunnel_stop,
        tunnel_commands::tunnel_status,
        tunnel_commands::tunnel_copy_ticket,
        tunnel_commands::tunnel_regenerate_ticket,
        tunnel_commands::tunnel_generate_ticket,
        join_commands::resolve_join_server_id,
        join_commands::join_server_by_id,
        server_id_commands::create_server_id,
        server_id_commands::resolve_server_id,
        server_id_commands::get_server_id,
        server_id_commands::list_server_ids,
        server_id_commands::update_server_id,
        server_id_commands::deactivate_server_id,
        server_id_commands::delete_server_id,
        server_id_commands::search_server_ids,
        update_commands::check_update,
        update_commands::open_download_url,
        update_commands::download_update,
        update_commands::install_update,
        update_commands::check_pending_update,
        update_commands::clear_pending_update,
        update_commands::restart_and_install,
        update_commands::download_update_from_debug_url,
        download_commands::download_file,
        download_commands::poll_task,
        download_commands::poll_all_downloads,
        download_commands::get_server_types,
        download_commands::get_versions_by_type,
        download_commands::get_download_info,
        download_commands::cancel_download_task,
        plugin_commands::list_plugins,
        plugin_commands::scan_plugins,
        plugin_commands::enable_plugin,
        plugin_commands::disable_plugin,
        plugin_commands::get_plugin_nav_items,
        plugin_commands::install_plugin,
        plugin_commands::get_plugin_icon,
        plugin_commands::get_plugin_settings,
        plugin_commands::set_plugin_settings,
        plugin_commands::get_plugin_css,
        plugin_commands::get_all_plugin_css,
        plugin_commands::delete_plugin,
        plugin_commands::delete_plugins,
        plugin_commands::check_plugin_update,
        plugin_commands::check_all_plugin_updates,
        plugin_commands::fetch_market_plugins,
        plugin_commands::fetch_market_categories,
        plugin_commands::fetch_market_plugin_detail,
        plugin_commands::install_from_market,
        plugin_commands::install_plugins_batch,
        plugin_commands::context_menu_callback,
        plugin_commands::context_menu_show_notify,
        plugin_commands::context_menu_hide_notify,
        plugin_commands::on_locale_changed,
        plugin_commands::component_mirror_register,
        plugin_commands::component_mirror_unregister,
        plugin_commands::component_mirror_clear,
        plugin_commands::on_page_changed,
        plugin_commands::get_plugin_component_snapshot,
        plugin_commands::get_plugin_ui_snapshot,
        plugin_commands::get_plugin_sidebar_snapshot,
        plugin_commands::get_plugin_context_menu_snapshot,
        plugin_commands::get_plugin_permission_logs,
        plugin_commands::get_permission_list,
        plugin_commands::get_plugin_permissions,
        server_plugin_commands::m_get_plugins,
        server_plugin_commands::m_toggle_plugin,
        server_plugin_commands::m_delete_plugin,
        server_plugin_commands::m_install_plugin,
        server_plugin_commands::m_get_plugin_config_files,
        logging_commands::get_logs,
        logging_commands::clear_logs,
        logging_commands::export_app_logs,
        logging_commands::check_developer_mode,
        #[cfg(debug_assertions)]
        debug_commands::debug_panic
    ]
}
