[package]
name = "sealantern-interface"
version = "1.2.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
path = "src/lib.rs"

[features]
default = []

[dependencies]
async-trait = "0.1.91"
tokio = { version = "1.53.1", features = ["rt", "macros"] }
serde = { version = "1", features = ["derive"] }
sealantern-core = { path = "../core" }

[dev-dependencies]
serde_json = "1"
